import Foundation

public enum SaveMode: Int, Codable, Sendable {
    case never = 0
    case onQuit = 1
    case afterEachClip = 2
}

public struct FlycutHotkey: Codable, Equatable, Sendable {
    public var keyCode: Int
    public var modifierFlags: Int

    public init(keyCode: Int, modifierFlags: Int) {
        self.keyCode = keyCode
        self.modifierFlags = modifierFlags
    }
}

public struct FlycutSettings: Codable, Equatable, Sendable {
    public var rememberPause = false
    public var capturePaused = false
    public var appearance = "system"
    public var recentCapacity = 40
    public var favoriteCapacity = 40
    public var menuPreviewCount = 10
    public var previewCharacterCount = 40
    public var hotkey = FlycutHotkey(keyCode: 9, modifierFlags: 1_179_648)
    public var saveMode = SaveMode.onQuit
    public var skipPasswordFields = true
    public var skipPasteboardTypes = true
    public var skippedPasteboardTypes = ["PasswordPboardType", "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
    public var skipPasswordLengths = false
    public var skippedPasswordLengths = [12, 20, 32]
    public var revealPasteboardTypes = false
    public var pasteMovesToTop = false
    public var cloudSyncEnabled = false
    public var menuIcon = 0
    public var bezelAlpha = 0.25
    public var stickyPalette = false
    public var wraparoundPalette = false
    public var openAtLogin = false
    public var menuSelectionPastes = true
    public var bezelWidth = 460.0
    public var bezelHeight = 700.0
    public var popUpAnimation = false
    public var displayClippingSource = true
    public var showHoverPreview = true
    public var saveForgottenClippings = false
    public var saveForgottenFavorites = true
    public var suppressAccessibilityAlert = false
    public var saveToLocation: URL?
    public var autoSaveToLocation: URL?

    public init() {}

    public mutating func validate() {
        if !["system", "light", "dark"].contains(appearance) { appearance = "system" }
        if recentCapacity < 1 { recentCapacity = 40 }
        if favoriteCapacity < 1 { favoriteCapacity = 40 }
        if menuPreviewCount < 1 { menuPreviewCount = 10 }
        if previewCharacterCount < 1 { previewCharacterCount = 40 }
        if !(0...127).contains(hotkey.keyCode) || hotkey.modifierFlags < 0 || hotkey.modifierFlags > 0xFFFF_FFFF {
            hotkey = FlycutHotkey(keyCode: 9, modifierFlags: 1_179_648)
        }
        bezelAlpha = bezelAlpha.isFinite ? min(max(bezelAlpha, 0), 1) : 0.25
        bezelWidth = bezelWidth.isFinite ? min(max(bezelWidth, 200), 1600) : 460
        bezelHeight = bezelHeight.isFinite ? min(max(bezelHeight, 160), 1200) : 700
        skippedPasswordLengths = skippedPasswordLengths.filter { $0 > 0 }
        if menuIcon < 0 || menuIcon > 2 { menuIcon = 0 }
        if cloudSyncEnabled { saveMode = .afterEachClip }
        if let url = saveToLocation, !url.isFileURL || url.absoluteString.utf8.count > 4096 { saveToLocation = nil }
        if let url = autoSaveToLocation, !url.isFileURL || url.absoluteString.utf8.count > 4096 { autoSaveToLocation = nil }
    }
}
