import XCTest
@testable import FlycutCore

final class CapturePolicyTests: XCTestCase {
    func testEmptyRejectedAndTopDuplicateAcceptedForRefresh() {
        let settings = FlycutSettings()
        XCTAssertFalse(CapturePolicy.accepts(text: "", advertisedTypes: ["public.utf8-plain-text"], settings: settings))
        XCTAssertTrue(CapturePolicy.accepts(text: "same", advertisedTypes: ["public.utf8-plain-text"], settings: settings))
        XCTAssertTrue(CapturePolicy.accepts(text: "different", advertisedTypes: ["public.utf8-plain-text"], settings: settings))
    }

    func testSensitiveTypesAreRejectedBeforeCapture() {
        let settings = FlycutSettings()
        for type in ["PasswordPboardType", "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"] {
            XCTAssertFalse(CapturePolicy.accepts(text: "secret", advertisedTypes: ["public.utf8-plain-text", type], settings: settings), type)
        }
    }

    func testOptionalLengthAndTypeRulesCanBeConfigured() {
        var settings = FlycutSettings()
        settings.skipPasswordLengths = true
        settings.skippedPasswordLengths = [4]
        XCTAssertFalse(CapturePolicy.accepts(text: "🔒abc", advertisedTypes: [], settings: settings))
        settings.skipPasswordLengths = false
        XCTAssertTrue(CapturePolicy.accepts(text: "🔒abc", advertisedTypes: [], settings: settings))
        settings.skippedPasteboardTypes = ["custom.secret"]
        XCTAssertFalse(CapturePolicy.accepts(text: "value", advertisedTypes: ["custom.secret"], settings: settings))
        settings.skipPasteboardTypes = false
        XCTAssertTrue(CapturePolicy.accepts(text: "value", advertisedTypes: ["custom.secret"], settings: settings))
    }
}
